apiVersion: v1
kind: Service
metadata:
  name: myserver
  namespace: default
  labels:
    app: myserver
spec:
  type: ClusterIP
  selector:
    app: myserver
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
